msu-anthropology/daea-fs18

sites/practice/practice.html
=> edited practice.html

sites/practice-stuff/practice-stuff.html
added practice-stuff folder & .html; changed site name, time period, author
=> added practice-stuff

sites/tel-el-amarna/tel-el-amarna.html
added tel el-amarna folder, img folder, tel el-amarna.html
=> added tel el-amarna

sites/tel-el-amarna/tel-el-amarna.html
=> changed time period

sites/tel-el-amarna/tel-el-amarna.html
added amarna folder, img folder, amarna.html
-checking for correct css
=> added amarna

sites/alexandria/alexandria.html
duplicated aa-template and renamed it to site, blah blah blah
=> added alexandria site files

sites/red-monastery/red-monastery.html
created folder for site; changed name of folder and html folder; added image folder within it; changed project metadata in html file.
=> site name and folders

sites/tipan-chen-uitz/tipan-chen-uitz.html
added TCU folder in sites folder
-created TCU.html
-created img folder
=> added new site folder - also still olde folders...delete them

sites/sac-uitz/sac-uitz.html
making sure template within html text is fine
-also making sure forking from repo is good
=> doing edits and such

sites/AA-template/gebel el-silsila/gebel el-silsia.html, sites/gebel el-silila/gebel el-silila.html
Added, site folder, img folder, added and edited site html
=> added site folder

sites/semna-south/test.html, sites/test/test.html
Site name, Semna South (Nubia) author (me), time period (1965-1920BC)
=> Added test site

sites/kerma/kerma.html
Created img folder and renamed site folder. Changed site name, time period, and author name.
=> Added and edited site folder

sites/kom-abu-bello/kom-abu-bello.html
Created folder for site Dom-Abu-Bello - Created image folder
- Created html file
=> added new site folder

sites/precint-of-mut/precint-of-mut.html
Added Precint of Mut folder in sites folder
-created Precinct of Mut html
-created img folder
=> Added new site folder.

sites/dier-el-ballas/dier-el-ballas.html
added new site folder, changed html, added img folder
=> added site file

sites/kom-ombo/kom-ombo.html
added new sight folder, html, "Kom Ombo"
=> Added sight file

sites/tell-edfu/tell-edfu.html
Renamed AA-template.html to site/tell-edfu.html
Created new folder titled img
Changed <h1>SITE NAME</h1> to <h1>Tell Edfu</h1>
Changed <h4>AUTHOR</h4> to <h4>Morgan Otero</h4>
=> Tell Edfu site file added 

sites/dashur/dashur.html
Added Dashur file folder, changed html name, added img file folder, and edited site name, time period, and author name
=> Added New Site (Dashur) Folder

sites/temple-of-hathor-dendra/tample-of-hathor-dendra.html
added site file,html
added img folder 
edited site name and author
=> Added site file 

sites/naga-ed-deir/naga-ed-deir.html, sites/tell-edfu/tell-edfu.html
Duplicated template folder and renamed html file
Added basic site information to the html file
=> Added my own site

sites/temple-of-amun-at-siwa/temple-of-amun-at-siwa.html
Changed site name to Temple of Amun at Siwa. Changed time period to 26th Dynasty. Changed author to Casey Hunter Carter. Added .img file.
=> Title Changes

sites/naga-ed-deir/naga-ed-deir.html
-added new blocks for each of the required sections
=> Submitting Milestone 1 (and added headers)

sites/temple-of-amun-at-siwa/temple-of-amun-at-siwa.html
Created section headings
Turning in Milestone 1 Assignment
=> Turning in Milestone 1 Assignment
